/* Creating Encrypted Diary Database */

CREATE DATABASE ENCRYPTED_DIARY_DB
  WITH FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'master' );
GO

/* Changing to the ENCRYPTED_DIARY_DB database */

USE ENCRYPTED_DIARY_DB;
GO


/* CREATING TABLE OF USERS */

CREATE TABLE Users (
    userID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    passHash NVARCHAR(255) NOT NULL,
    dateCreated DATE
);

/* CREATING TABLE OF USERDATA */
CREATE TABLE UserData (
    userDataId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    securityQuestion NVARCHAR(255) NULL,
    securityAnswer NVARCHAR(255) NULL,
    numDocuments INT NOT NULL,
    userID INT FOREIGN KEY REFERENCES Users(userID)
);

/* CREATING TABLE OF USERDOCUMENTS */
CREATE TABLE UserDocuments as FILETABLE(
    userDocumentsID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    userDocumentName VARCHAR (25) NOT NULL,
    userDocumentContents VARBINARY (MAX) FILESTREAM NULL,
    encryptionMethod NVARCHAR(30) NOT NULL,
    decryptionMethod NVARCHAR(30) NOT NULL,
    userID INT FOREIGN KEY REFERENCES Users(userID)
);

