/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EncryptedDiary.app;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import java.awt.*;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args){

        DiaryLoginPage login = new DiaryLoginPage();
        login.setVisible(true);

    }

}

//TODO: CONSTRUCT APPLICATION CLASS SO THAT IT HANDLES THE PROCESS OF SWITCHING FROM PAGE TO PAGE AND DOESN'T
// OUTSOURCE IT TO OTHER CLASSES
