/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EncryptedDiary.app;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args){

        DiaryLoginPage loginPage = new DiaryLoginPage();

    }

//    public static void main(String[] args) {
//
////        DiaryEditorPage page = new DiaryEditorPage();
//
//        try {
//            Cipher cipher = Cipher.getInstance("AES");
//
//            DiaryCipher myDiaryCipher = new DiaryCipher();
//            SecretKey key = myDiaryCipher.getKey();
//
//            byte[] encryptedBytes = myDiaryCipher.encryptText("HELLO WORLD", key, cipher);
//
//            String encryptedString = new String(encryptedBytes);
//
//            System.out.println(encryptedString);
//
//            String decryptedString = myDiaryCipher.decryptString(encryptedBytes, key, cipher);
//
//            System.out.println(decryptedString);
//
//        } catch (Exception ex) {
//            System.out.println(ex.getMessage());
//        }
//    }

}
